### ISSUE TITLE
Document that `take` uses spinning

### ISSUE THREAD

**Issue by tmandry** [hawkw/sharded-slab#20]
Spinning has different performance/energy characteristics than mutexes/condition vars, and it would be good to document that this is what `take` does.

**Comment by hawkw** [comment]
Other options include:
- Actually using a condvar here. The reason we're not using one _now_ is that it would only be used in `take`, and would mean adding a mutex/condvar pair to every slot. This would mean two heap allocations per slot, plus increasing the size of each slot itself by 32 bytes (on linux/x86_64, see https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5c07e4a6cbf9e3755ff5543a9062d6d9)
- Just remove this API entirely in 0.1. I'm not sure how much of a use-case there is for it OTTOMH (`tracing-subscriber` doesn't use it).

**Comment by hawkw** [comment]
Another option is that we could consider adding a proper backoff here. We would still be spinning, but could have the thread sleep while spinning rather than just emitting `pause` instructions. That would be an obstacle to porting to `no_std`, but this code currently doesn't work on `no_std`, and we could just feature flag it.

This might be a good compromise between not burning CPU in a tight loop and having to allocate a mutex/condvar pair for every slot.
